# Starship Configuration
# See https://starship.rs/config/ for more information

# Increase command timeout to 5 seconds (default is 1 second)
command_timeout = 5000
right_format = '$all'
format = """$directory$git_status$git_state$character"""

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
truncation_length = 63
style = "purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "yellow"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

# Optimize git operations
[git_metrics]
disabled = true  # Disable git metrics to reduce git operations

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold blue" 

[nodejs]
format= '[$symbol($version )]($style)'
